
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.25.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace SplitViewCommander {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.TableView tableView;
        
        private Terminal.Gui.Window window;
        
        private Terminal.Gui.Window window2;
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.Button button1;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileF9Menu;
        
        private Terminal.Gui.MenuItem editMeMenuItem;
        
        private Terminal.Gui.MenuItem menuItem;
        
        private Terminal.Gui.MenuItem menuItem2;
        
        private Terminal.Gui.MenuBarItem markMenu;
        
        private Terminal.Gui.MenuItem editMeMenuItem2;
        
        private Terminal.Gui.MenuBarItem optionsMenu;
        
        private Terminal.Gui.MenuItem editMeMenuItem3;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.button1 = new Terminal.Gui.Button();
            this.label1 = new Terminal.Gui.Label();
            this.window2 = new Terminal.Gui.Window();
            this.window = new Terminal.Gui.Window();
            this.tableView = new Terminal.Gui.TableView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Rounded;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Press Ctrl+Q to quit";
            this.tableView.Width = 50;
            this.tableView.Height = 5;
            this.tableView.X = 0;
            this.tableView.Y = 5;
            this.tableView.Visible = true;
            this.tableView.Data = "tableView";
            this.tableView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tableView.FullRowSelect = false;
            this.tableView.Style.AlwaysShowHeaders = true;
            this.tableView.Style.ExpandLastColumn = true;
            this.tableView.Style.InvertSelectedCellFirstCharacter = false;
            this.tableView.Style.ShowHorizontalHeaderOverline = true;
            this.tableView.Style.ShowHorizontalHeaderUnderline = true;
            this.tableView.Style.ShowVerticalCellLines = true;
            this.tableView.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableViewTable;
            tableViewTable = new System.Data.DataTable();
            System.Data.DataColumn tableViewTableColumn0;
            tableViewTableColumn0 = new System.Data.DataColumn();
            tableViewTableColumn0.ColumnName = "Column 0";
            tableViewTable.Columns.Add(tableViewTableColumn0);
            System.Data.DataColumn tableViewTableColumn1;
            tableViewTableColumn1 = new System.Data.DataColumn();
            tableViewTableColumn1.ColumnName = "Column 1";
            tableViewTable.Columns.Add(tableViewTableColumn1);
            System.Data.DataColumn tableViewTableColumn2;
            tableViewTableColumn2 = new System.Data.DataColumn();
            tableViewTableColumn2.ColumnName = "Column 2";
            tableViewTable.Columns.Add(tableViewTableColumn2);
            System.Data.DataColumn tableViewTableColumn3;
            tableViewTableColumn3 = new System.Data.DataColumn();
            tableViewTableColumn3.ColumnName = "Column 3";
            tableViewTable.Columns.Add(tableViewTableColumn3);
            this.tableView.Table = tableViewTable;
            this.Add(this.tableView);
            this.window.Width = Dim.Percent(40f);
            this.window.Height = 5;
            this.window.X = 12;
            this.window.Y = 14;
            this.window.Visible = true;
            this.window.Modal = false;
            this.window.IsMdiContainer = false;
            this.window.Data = "window";
            this.window.Border.BorderStyle = Terminal.Gui.BorderStyle.Rounded;
            this.window.Border.Effect3D = false;
            this.window.Border.Effect3DBrush = null;
            this.window.Border.DrawMarginFrame = true;
            this.window.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Title = "";
            this.Add(this.window);
            this.window2.Width = Dim.Percent(40f);
            this.window2.Height = 5;
            this.window2.X = 92;
            this.window2.Y = 14;
            this.window2.Visible = true;
            this.window2.Modal = false;
            this.window2.IsMdiContainer = false;
            this.window2.Data = "window2";
            this.window2.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.window2.Border.Effect3D = false;
            this.window2.Border.Effect3DBrush = null;
            this.window2.Border.DrawMarginFrame = true;
            this.window2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window2.Title = "";
            this.Add(this.window2);
            this.label1.Width = 4;
            this.label1.Height = 1;
            this.label1.X = Pos.Center();
            this.label1.Y = Pos.Center();
            this.label1.Visible = true;
            this.label1.Data = "label1";
            this.label1.Text = "Hello World";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.button1.Width = 12;
            this.button1.Height = 1;
            this.button1.X = Pos.Center();
            this.button1.Y = Pos.Center() + 1;
            this.button1.Visible = true;
            this.button1.Data = "button1";
            this.button1.Text = "Click Me";
            this.button1.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button1.IsDefault = false;
            this.Add(this.button1);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.fileF9Menu = new Terminal.Gui.MenuBarItem();
            this.fileF9Menu.Title = "_File (F9)";
            this.editMeMenuItem = new Terminal.Gui.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.menuItem = new Terminal.Gui.MenuItem();
            this.menuItem.Title = "";
            this.menuItem.Data = "menuItem";
            this.menuItem2 = new Terminal.Gui.MenuItem();
            this.menuItem2.Title = "";
            this.menuItem2.Data = "menuItem2";
            this.fileF9Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem,
                    this.menuItem,
                    this.menuItem2};
            this.markMenu = new Terminal.Gui.MenuBarItem();
            this.markMenu.Title = "Mark";
            this.editMeMenuItem2 = new Terminal.Gui.MenuItem();
            this.editMeMenuItem2.Title = "Edit Me";
            this.editMeMenuItem2.Data = "editMeMenuItem2";
            this.markMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem2};
            this.optionsMenu = new Terminal.Gui.MenuBarItem();
            this.optionsMenu.Title = "Options";
            this.editMeMenuItem3 = new Terminal.Gui.MenuItem();
            this.editMeMenuItem3.Title = "Edit Me";
            this.editMeMenuItem3.Data = "editMeMenuItem3";
            this.optionsMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem3};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileF9Menu,
                    this.markMenu,
                    this.optionsMenu};
            this.Add(this.menuBar);
        }
    }
}
